### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by gileri** [severak/lunarender#1]
I don't have much exeperience on lua, but I can't manage to launch lunarender on linux ('%' and before is my bash prompt):

% lua bin/lunarender.lua
lua: bin/lunarender.lua:5: module 'lunarender.reader' not found

% PATH=.:./bin:./lib:./lib/lua:$PATH lua bin/lunarender.lua
lua: bin/lunarender.lua:5: module 'lunarender.reader' not found

lunarender/lib/lua% lua ../../bin/lunarender.lua 
lua: ./lunarender/reader.lua:5: module 'lxp' not found

**Comment by severak** [comment]
1. run lua and then `print(package.path)`
2. copy files from `lunarender/lib/lua` to path reported by previous step
3. install [LuaExpat](https://matthewwild.co.uk/projects/luaexpat/)
4. try again rendering

unfortunately not having linux box at home to trying it by myself

**Comment by gileri** [comment]
Thanks to your advice, it's working now !
I thought it was packaged because of the `lib/lua/lxp/lom.lua` file, but indeed it was missing.
